### PR TITLE
fixed the bug when future restarts the state goes to ready instead of pending

### LINKED ISSUE #2812: `Resource` of `use_resource` state should go back to `Pending` when a dependency changes.
**Problem**

When using `use_resource` with reactive, dependencies, the state go from `Pending` to `Ready`, but when the future is restarted (when a dependency changes), the state remains `Ready`.

This should be pretty easy to fix, just change the implementation here: https://github.com/DioxusLabs/dioxus/blob/b97e607aca0bd8a12971fcf403908addf9a45dd7/packages/hooks/src/use_resource.rs#L31

Note that the behaviour of `SuspenseBoundary` would change. It would display the fallback each time the future is restarted. But that would make more sense in my opinion.

A related issue would be to update the docs of `use_future` to clarify that it will not re-run when the dependencies changes, and that one should use `use_resource` instead.

**Environment:**
 - Dioxus version:  `master`

### PR DESCRIPTION
**Pull request by avij1109**
This PR fixes the bug when future is restarted, the state remains ready instead of pending

Fixes #2812

### CODE REVIEW

File: packages/hooks/src/use_resource.rs [hunk 1]
```diff
@@ -28,16 +28,19 @@ where
         (rc, Rc::new(Cell::new(Some(changed))))
     });
 
-    let cb = use_callback(move |_| {
+    llet cb = use_callback(move |_| {
```
Comment (candunaj) [inline packages/hooks/src/use_resource.rs:31]: There is a typo. llet should be let.

**Review by jkelleyrtp — APPROVED** [review]
