### PR TITLE
fix: symbol mismatch  in object file

### LINKED ISSUE #4169: Symbol type mismatch between `STT_FUNC` and `STT_TLS`
**Problem**
Hot-patching fails to reload on function

**Steps To Reproduce**

- `dx serve --hot-patch`
- Depend on some runtime code that utilizes thread channels
- update some function (in this case, some function that updates camera transform. I did not call a channel directly here.)

**Logs**
(This goes on, I believe this is enough to identify ths issue)
```console
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.61pt1o0nksba95ejv4uin9bek.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: rayon_core::registry::WORKER_THREAD_STATE::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h5b72738f05b71bcb
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.61pt1o0nksba95ejv4uin9bek.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: std::sync::mpmc::context::Context::with::CONTEXT::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h34901b78060da703
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.2jwtpw1wo0vyvk54rrtb3s1lo.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: rayon_core::registry::WORKER_THREAD_STATE::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h5b72738f05b71bcb
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.6qf93jwpagnd6pzcx2nklx9e9.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: std::hash::random::RandomState::new::KEYS::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h6b307b4d5c9f8d41
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.2upke50tzcrvylc87xbnhselq.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: rayon_core::registry::Registry::in_worker_cold::LOCK_LATCH::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h6c1a7cebcbb48869
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.6qf93jwpagnd6pzcx2nklx9e9.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: std::sync::mpmc::waker::current_thread_id::DUMMY::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h40d6ba24d35890da
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.c6jiucc0gjo21hfq5zae0jrzw.rcgu.o as STT_TLS
mold: warning: symbol type mismatch: std::sync::mpmc::context::Context::with::CONTEXT::_$u7b$$u7b$constant$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::VAL::h34901b78060da703
>>> defined in /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/stub.o as STT_FUNC
>>> defined in /home/adamime/repo/red-room3d/target/x86_64-unknown-linux-gnu/debug/deps/red_room3d-30d5ca6d8a32b76b.61pt1o0nksba95ejv4uin9bek.rcgu.o as STT_TLS
23:12:29 [dev] Patching /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/red-room3d -> /home/adamime/repo/red-room3d/target/dx/red-room3d/debug/linux/app/libred-room3d-patch-1747883539211.so
23:12:29 [dev] Hot-patching: /src/gameplay/camera.rs took 10331ms
23:12:30 [dev] Application [linux] exited with error: signal: 8 (SIGFPE) (core dumped)
```

**Environment:**
- Dioxus version: `dioxus 0.7.0-alpha.0 (ab76d90)`
- Rust version: `rustc 1.87 stable`
- OS info: `Linux 6.11 - Ubuntu 24.04`
- App platform: `Desktop`

I'm happy to produce an MRE if this log doesn't identify the issue! Seems like it's symbols. Seems tangentially related to #4152. I think this fix uncovered a symbol mismatch.

related to https://github.com/rui314/mold/issues/1093

### PR DESCRIPTION
**Pull request by dsgallups**
fixes #4169

### CODE REVIEW

**Comment by dsgallups** [comment]
way off the mark

File: packages/cli/src/build/patch.rs [hunk 1]
```diff
@@ -758,10 +758,13 @@ pub fn create_undefined_symbol_stub(
     let mut undefined_symbols = HashSet::new();
     let mut defined_symbols = HashSet::new();
 
+    let mut symbol_map = HashMap::new();
```
Comment (dsgallups) [inline packages/cli/src/build/patch.rs:761]: this smells

File: packages/cli/src/build/patch.rs [hunk 2]
```diff
@@ -1052,6 +1056,38 @@ pub fn create_undefined_symbol_stub(
                     flags: object::SymbolFlags::None,
                 });
             }
+            SymbolKind::Tls => {
+                let tls_section = obj.section_id(StandardSection::Tls);
+
+                let pointer_width = |triple: &Triple| match triple.pointer_width().unwrap() {
+                    PointerWidth::U16 => 2,
```
Comment (dsgallups) [inline packages/cli/src/build/patch.rs:1063]: dont think we're running on 16 bit machines but like, why not

**Review by dsgallups — COMMENTED** [review]
Please edit this PR as I am sure this is amiss for a few reasons
1. I'm unsure if this is `mold` specific behavior
2. I cannot find a reference for how rust gives equivalency between`STT_FUNC` and `STT_TLS`
3. I cannot reproduce on windows due to #4159, and I will only have access to mac in the AM to make sure this is inconsequential/beneficial.

Did not update the comment for the `SymbolKind::Text` arm

**Comment by jkelleyrtp** [comment]
I think we can use the section of the symbol to determine which type of TLS it is. We do need both. Will take a poke at fixing it for the STT type. Do you have any projects or repro that includes both?

**Comment by dsgallups** [comment]
@jkelleyrtp Would it still be beneficial to have a MRE?
