### PR TITLE
Fix: #2604, Fix: #2240, Fix: #2341, Fix #1355 - Better error handling and and spaces handling in autofmt

### LINKED ISSUE #1355: `#[dxfmt::skip]` similar to `#[rustfmt::skip] `
## Specific Demand

I would like a macro to flag portions of code that you don't want `dx fmt` to touch.
This would be handy on codebases that you would want `rustfmt` to format your structs:

```rust
my_thing: Thing = Thing {...}
```

And `dx fmt` would just format this as a component.

Then, `rustfmt` and Dioxus would fight over the formatting.
I can always turn `rustfmt` off but I cannot do the same with Dioxus formatter.

## Implement Suggestion

Similar to `#[rustfmt::skip]`

### PR DESCRIPTION
**Pull request by jkelleyrtp**
This fixes a few bugs in autofmt such that fewer comments get eaten.

- [x] Fix: #2604 
- [x] Fix: #2240
- [x] Fix: #1355 
- [x] Fix: #1488 
- [x] Fix: #2341
- [x] Fix: #1492

However, it still doesn't fix comments getting eaten in handlers - this will require rustfmt integration

We now respect rustfmt::skip settings as well as rustfmt.toml

### CODE REVIEW

File: packages/autofmt/src/collect_macros.rs [hunk 1]
```diff
@@ -3,37 +3,66 @@
...
-        file,
-    );
+    let mut collector = MacroCollector::new(&mut macros);
+    MacroCollector::visit_file(&mut collector, file);
     macros
 }
 
 struct MacroCollector<'a, 'b> {
     macros: &'a mut Vec<CollectedMacro<'b>>,
+    skip_stack: Vec<()>,
```
Comment (ealmloff) [inline packages/autofmt/src/collect_macros.rs:19]: This could be usize

File: packages/autofmt/src/prettier_please.rs [hunk 2]
```diff
@@ -1,153 +1,159 @@
...
+                i.path = syn::parse_str(MARKER).unwrap();
+                i.tokens = Default::default();
+
+                // Push out the indent level of the formatted block if it's multiline
+                // Normally we'd use a `\n` as the delimiter, but we actually want to make sure
+                // any block-level things are indented properly
+                //
+                // we should really just be parsing the block here and using the same heuristic
+                // rsx_call uses (short strings are inlined, all others are multiline
+                if formatted.contains('{') {
```
Comment (ealmloff) [inline packages/autofmt/src/prettier_please.rs:50]: Will this format "{hello world}" as a multi-line string?

File: packages/autofmt/src/writer.rs [hunk 3]
```diff
@@ -114,66 +119,441 @@ impl<'a> Writer<'a> {
...
+
+    pub fn write_body_nodes(&mut self, children: &[BodyNode]) -> Result {
+        let mut iter = children.iter().peekable();
+
+        while let Some(child) = iter.next() {
+            if self.current_span_is_primary(child.span().start()) {
+                self.write_comments(child.span().start())?;
+            };
+            self.out.tab()?;
+            self.write_ident(child)?;
```
Comment (ealmloff) [inline packages/autofmt/src/writer.rs:246]: This should be write_body?

File: packages/autofmt/src/writer.rs [hunk 4]
```diff
@@ -114,66 +119,441 @@ impl<'a> Writer<'a> {
...
+                write!(self.out, " ")?;
+
+                self.write_attributes(attributes, spreads, true, brace, has_children)?;
+
+                if !children.is_empty() && !attributes.is_empty() {
+                    write!(self.out, " ")?;
+                }
+
+                for child in children.iter() {
+                    self.write_ident(child)?;
```
Comment (ealmloff) [inline packages/autofmt/src/writer.rs:355]: Do we need to insert spaces between children here?

File: packages/autofmt/src/writer.rs [hunk 5]
```diff
@@ -114,66 +119,442 @@ impl<'a> Writer<'a> {
...
+        let cond = self.unparse_expr(&if_chain.condition);
+        write!(self.out, "if {cond} {{ ")?;
+        self.write_attribute_value(&if_chain.then_value)?;
+        write!(self.out, " }}")?;
+        match if_chain.else_value.as_deref() {
+            Some(AttributeValue::IfExpr(else_if_chain)) => {
+                write!(self.out, "else ")?;
+                self.write_attribute_if_chain(else_if_chain)?;
+            }
+            Some(other) => {
```
Comment (ealmloff) [inline packages/autofmt/src/writer.rs:546]: I think this should be `else {{ `

File: packages/autofmt/src/writer.rs [hunk 6]
```diff
@@ -262,13 +650,16 @@ impl<'a> Writer<'a> {
                     .unwrap_or_default();
                 condition_len + value_len + if_len + brace_len + space_len + else_len
```
Comment (ealmloff) [inline packages/autofmt/src/writer.rs:651]: Not caused by this PR, but the else_len calculation is wrong

File: packages/autofmt/src/writer.rs (hunk 4 above)
Comment (ealmloff) [reply packages/autofmt/src/writer.rs:356]: No because we only do single line when there is one child

File: packages/rsx/src/literal.rs [hunk 7]
```diff
@@ -151,6 +151,14 @@ pub struct HotReloadFormattedSegment {
     pub dynamic_node_indexes: Vec<DynIdx>,
 }
 
+impl HotReloadFormattedSegment {
+    /// This mnethod is very important!
+    /// Deref + Spanned + .span() methods leads to name coliisions
```
Comment (ealmloff) [inline packages/rsx/src/literal.rs:156]: typos

**Review by ealmloff — APPROVED** [review]
