### PR TITLE
Handle abort diffing

### LINKED ISSUE #724: panic when switch from a None Element to a normal one (dioxus 0.3.1)
```rust
fn app(cx: Scope) -> Element {
    let count = use_state(cx, || 0);
    use_future(&cx, (), |_| {
        to_owned![count];
        async move {
            loop {
                tokio::time::sleep(Duration::from_millis(500)).await;
                count.modify(|v| v + 1);
            }
        }
    });

    println!("{count}");

    let node = if **count < 3 {
        rsx!(Test1 {})
    } else {
        rsx!(Test2 {})
    };
    render!(node)
}

fn Test1(cx: Scope) -> Element {
    None
}

fn Test2(cx: Scope) -> Element {
    render!(h1 {"Test2"})
}
```
```
0
1
2
3
thread 'main' panicked at 'assertion failed: self.mutations.edits.len() > pre_edits', .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:224:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:115
   3: dioxus_core::virtual_dom::VirtualDom::replace_vcomponent
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:224
   4: dioxus_core::virtual_dom::VirtualDom::diff_vcomponent
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:178
   5: dioxus_core::diff::impl$0::light_diff_templates::closure$0
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:278
   6: core::iter::traits::iterator::Iterator::for_each::call::closure$0<tuple$<usize,tuple$<ref$<dioxus_core::nodes::VComponent>,ref$<dioxus_core::nodes::VComponent> > >,dioxus_core::diff::impl$0::light_diff_templates::closure_env$0>
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\traits\iterator.rs:828
   7: core::iter::adapters::enumerate::impl$1::fold::enumerate::closure$0<tuple$<ref$<dioxus_core::nodes::VComponent>,ref$<dioxus_core::nodes::VComponent> >,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<tuple$<usize,tuple$<ref$<
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\adapters\enumerate.rs:106
   8: core::iter::traits::iterator::Iterator::fold<alloc::vec::into_iter::IntoIter<tuple$<ref$<dioxus_core::nodes::VComponent>,ref$<dioxus_core::nodes::VComponent> >,alloc::alloc::Global>,tuple$<>,core::iter::adapters::enumerate::impl$1::fold::enumerate::closur
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\traits\iterator.rs:2414
```

```rust
fn app(cx: Scope) -> Element {
    let count = use_state(cx, || 0);
    use_future(&cx, (), |_| {
        to_owned![count];
        async move {
            loop {
                tokio::time::sleep(Duration::from_millis(500)).await;
                count.modify(|v| v + 1);
            }
        }
    });

    println!("{count}");

    let node = if **count < 3 {
        rsx!(Test1 { num: **count })
    } else {
        rsx!(Test2 {})
    };
    render!(node)
}

#[inline_props]
fn Test1(cx: Scope, num: i32) -> Element {
    if num == &2 {
        return None;
    }
    render!(h1 {"{num}"})
}

fn Test2(cx: Scope) -> Element {
    render!(h1 {"Test2"})
}
```
```
0
1
2
thread 'main' panicked at 'not yet implemented', .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:69:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:115
   3: dioxus_core::virtual_dom::VirtualDom::diff_ok_to_err
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:69
   4: dioxus_core::virtual_dom::VirtualDom::diff_scope
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:40
   5: dioxus_core::virtual_dom::VirtualDom::diff_vcomponent
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:203
   6: dioxus_core::virtual_dom::VirtualDom::diff_dynamic_node
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:146
   7: dioxus_core::diff::impl$0::diff_node::closure$1
             at .cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\dioxus-core-0.3.0\src\diff.rs:128
   8: core::iter::traits::iterator::Iterator::for_each::call::closure$0<tuple$<usize,tuple$<ref$<enum2$<dioxus_core::nodes::DynamicNode> >,ref$<enum2$<dioxus_core::nodes::DynamicNode> > > >,dioxus_core::diff::impl$0::diff_node::closure_env$1>
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\traits\iterator.rs:828
   9: core::iter::adapters::enumerate::impl$1::fold::enumerate::closure$0<tuple$<ref$<enum2$<dioxus_core::nodes::DynamicNode> >,ref$<enum2$<dioxus_core::nodes::DynamicNode> 
> >,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<tuple
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\adapters\enumerate.rs:106
  10: core::iter::traits::iterator::Iterator::fold<core::iter::adapters::zip::Zip<core::slice::iter::Iter<enum2$<dioxus_core::nodes::DynamicNode> >,core::slice::iter::Iter<enum2$<dioxus_core::nodes::DynamicNode> > >,tuple$<>,core::iter::adapters::enumerate::imp
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\traits\iterator.rs:2414
  11: core::iter::adapters::enumerate::impl$1::fold<core::iter::adapters::zip::Zip<core::slice::iter::Iter<enum2$<dioxus_core::nodes::DynamicNode> >,core::slice::iter::Iter<enum2$<dioxus_core::nodes::DynamicNode> > >,tuple$<>,core::iter::traits::iterator::Itera
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\adapters\enumerate.rs:112
  12: core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::enumerate::Enumerate<core::iter::adapters::zip::Zip<core::slice::iter::Iter<enum2$<dioxus_core::nodes::DynamicNode> >,core::slice::iter::Iter<enum2$<dioxus_core::nodes::DynamicNode> >
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\iter\traits\iterator.rs:831
```

### PR DESCRIPTION
**Pull request by Demonthos**
Handles diffing of aborted components (components that return None)

fixes #724

### CODE REVIEW

File: packages/core/src/diff.rs [hunk 1]
```diff
@@ -65,8 +65,26 @@ impl<'b> VirtualDom {
         //
     }
 
-    fn diff_ok_to_err(&mut self, _l: &'b VNode<'b>, _p: &'b VPlaceholder) {
-        todo!()
+    fn diff_ok_to_err(&mut self, l: &'b VNode<'b>, p: &'b VPlaceholder) {
+        let id = self.next_null();
```
Comment (Demonthos) [inline packages/core/src/diff.rs:69]: Elements is only used for bubbling events and events should never be created on placeholders

**Comment by Demonthos** [comment]
Running the fuzzing test in #721, this branch passes and with the unsafe fixes merged into master recently it passes miri as well

**Comment by jkelleyrtp** [comment]
Way better than using null, totally forgot that NonNull was an Option. Thanks!!

**Review by jkelleyrtp — APPROVED** [review]
