### PR TITLE
fix: feature gate tokio and tracing

### LINKED ISSUE #4641: dioxus-native fails to compile with tracing or net feature turned off
**Problem**

Turning off tracing or net causes dioxus-native to fail to compile even though its marked as a feature flag that can be disabled.

```rust
dioxus-d8abd2ecf6e8b5b4/5ebde96/packages/native/src/assets.rs:38:21
   |
38 |                     tracing::trace!("fetching asset  from file system success {request:#?}");
   |                     ^^^^^^^ use of unresolved module or unlinked crate `tracing`
```
**Steps To Reproduce**

disable default features for dioxus-native
attempt to compile dioxus native

**Environment:**

- Dioxus version:  commit 5ebde96
- Rust version: 1.88
- OS info:  ubuntu 24
- App platform:  desktop native

### PR DESCRIPTION
**Pull request by omar-mohamed-khallaf**
Fixes #4641.

### CODE REVIEW

File: packages/native/src/lib.rs [hunk 1]
```diff
@@ -82,10 +82,12 @@ pub fn launch_cfg_with_props<P: Clone + 'static, M: 'static>(
     let event_loop = create_default_event_loop::<BlitzShellEvent>();
 
     // Turn on the runtime and enter it
+    #[cfg(feature = "net")]
     let rt = tokio::runtime::Builder::new_multi_thread()
```
Comment (omar-khallaf) [inline packages/native/src/lib.rs:86]: Is `tokio` required?

Comment (nicoburns) [reply packages/native/src/lib.rs:86]: For blitz-net, yes it is currently as it's using `reqwest`. We want to add `ureq` backend at some point (which would probably use a `rayon` threadpool instead).

Comment (nicoburns) [reply packages/native/src/lib.rs:86]: I also want to add a "data-uri and assets only" (but not http(s)) option, which wouldn't need tokio.

Comment (omar-khallaf) [reply packages/native/src/lib.rs:86]: Ok, good thing I didn't delete it.

**Review by nicoburns — APPROVED** [review]
