### PR TITLE
Fix duplicate example and test names

### LINKED ISSUE #1001: Output File Name Collisions when Running Build and Test in Dioxus Repo
**Problem**
After Running these commands in Dioxus Repo: 
```
cargo build --all --tests --examples
cargo test --all --tests
```

Receive these Errors: 
```
warning: output filename collision.
The example target `simple` in package `dioxus-router v0.3.0 (/workspaces/dioxus/packages/router)` has the same output filename as the example target `simple` in package `dioxus-native-core v0.2.0 (/workspaces/dioxus/packages/native-core)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/simple
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `simple` in package `dioxus-router v0.3.0 (/workspaces/dioxus/packages/router)` has the same output filename as the example target `simple` in package `dioxus-native-core v0.2.0 (/workspaces/dioxus/packages/native-core)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/simple.dwp
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `all_events` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `all_events` in package `dioxus-examples v0.0.0 (/workspaces/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/all_events
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `all_events` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `all_events` in package `dioxus-examples v0.0.0 (/workspaces/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/all_events.dwp
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `components` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `components` in package `dioxus-guide v0.0.1 (/workspaces/dioxus/docs/guide)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/components
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `components` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `components` in package `dioxus-guide v0.0.1 (/workspaces/dioxus/docs/guide)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/components.dwp
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `readme` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `readme` in package `dioxus-examples v0.0.0 (/workspaces/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/readme
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `readme` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `readme` in package `dioxus-examples v0.0.0 (/workspaces/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/readme.dwp
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `stress` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `stress` in package `dioxus v0.3.2 (/workspaces/dioxus/packages/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/stress
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `stress` in package `dioxus-tui v0.2.2 (/workspaces/dioxus/packages/dioxus-tui)` has the same output filename as the example target `stress` in package `dioxus v0.3.2 (/workspaces/dioxus/packages/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/stress.dwp
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `counter` in package `rink v0.2.2 (/workspaces/dioxus/packages/rink)` has the same output filename as the example target `counter` in package `dioxus-examples v0.0.0 (/workspaces/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/counter
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The example target `counter` in package `rink v0.2.2 (/workspaces/dioxus/packages/rink)` has the same output filename as the example target `counter` in package `dioxus-examples v0.0.0 (/workspaces/dioxus)`.
Colliding filename is: /workspaces/dioxus/target/debug/examples/counter.dwp
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```

**Steps To Reproduce**

Run folloqing commands from Dioxus Repo:
```
cargo build --all --tests --examples
cargo test --all --tests
```

- 
- 
- 

**Expected behavior**

No name collisions

**Screenshots**

**Environment:**
 - Dioxus version: Master
 - Rust version: 1.67.0, `nightly`
 - OS info: Manjaro or Debian
 - App platform: All

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x ] I don't have time to fix this right now, but maybe later

### PR DESCRIPTION
**Pull request by Demonthos**
Fixes #1001

### CODE REVIEW

File: packages/dioxus-tui/examples/components.rs [hunk 1]
```diff
@@ -1,67 +0,0 @@
-#![allow(non_snake_case)]
```
Comment (Demonthos) [inline packages/dioxus-tui/examples/components.rs:1]: This example was just a better version of the quadrants example, so this PR moves it into the quadrants example
