### PR TITLE
Fix repeated subscription to dropped scope leak

### LINKED ISSUE #3526: bug: Potential memory leak when calling components
**Problem**

It seems that simply calling components leaves a small leak that `v0.5` didn't have, its true that the following code is very awkward and definitely not real world, but the root issue might be affecting other scenarios that are actually more common and with worse outcomes.

**Steps To Reproduce**

```rs
#![allow(non_snake_case)]
use dioxus::prelude::dioxus_core::NoOpMutations;
use dioxus::prelude::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    fn app() -> Element {
        

        rsx! {
            Spammer {}
            Spammer {}
            Spammer {}
            Spammer {}
        }
    }

    fn Spammer() -> Element {
        let mut count = use_signal(|| 0);

        use_hook(|| spawn(async move {
            loop {
                tokio::time::sleep(std::time::Duration::from_nanos(1)).await;
                let val = *count.peek_unchecked();
                if val == 70 {
                    count.set(0);
                } else {
                    count.set(val + 1);
                }
            }
        }));

        rsx! {
            for el in 0..*count.read() {
				// To avoid the leak simply replace this by `div {`
                Comp {
                    key: "{el}",
                }
            }
        }
    }
	

    #[component]
    fn Comp() -> Element {
        rsx!(
            div { }
        )
    }

    // create the vdom, the real_dom, and the binding layer between them
    let mut vdom = VirtualDom::new(app);

    vdom.rebuild(&mut NoOpMutations);

    // we need to run the vdom in a async runtime
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?
        .block_on(async {
            loop {
                // wait for the vdom to update
                vdom.wait_for_work().await;

                // get the mutations from the vdom
                 vdom.render_immediate(&mut NoOpMutations);
            }
        })
}
```

**Environment:**
 - Dioxus version:  0.6.1
 - Rust version:    1.82
 - OS info:         Windows
 - App platform:   just core crates, no renderer

### PR DESCRIPTION
**Pull request by ealmloff**
When reactive scopes drop, they didn't remove themselves from signal's subscriber list until the signal was written to. That causes issues with the built in hot reloading signal which is never written to. This PR removes the subscriptions when the reactive scope drops

Fixes #3526

### CODE REVIEW

File: packages/core/src/reactive_context.rs [hunk 1]
```diff
@@ -311,3 +311,15 @@ struct Inner {
...
+
+impl Drop for Inner {
+    fn drop(&mut self) {
+        let self_ = self
+            .self_
+            .expect("self_ should be set during initialization");
+        let old_subscribers = std::mem::take(&mut self.subscribers);
+        for subscriber in old_subscribers {
+            subscriber.0.lock().unwrap().remove(&self_);
+        }
```
Comment (jkelleyrtp) [inline packages/core/src/reactive_context.rs:323]: can we make these not unwrap/expect and instead use options/if/else?

I'm sure it won't be an issue but just want to guard against panics in drops since that can cause an abort.

**Review by jkelleyrtp — CHANGES_REQUESTED** [review]

**Review by jkelleyrtp — APPROVED** [review]

**Comment by marc2332** [comment]
Nice work!
