### PR TITLE
Fix hydration of suspense fragments that contain text nodes

### LINKED ISSUE #3041: `use_server_future` Hydration error
**Problem**
- main.rs
```rust
    #[cfg(feature = "web")]
    dioxus_web::launch::launch(App, vec![], dioxus_web::Config::new().hydrate(true));

    #[cfg(feature = "server")]
    dioxus::launch(App);
```

- component.rs
  - `use_resource` works properly.
  - `use_server_future` causes hydration error.
 
```rust
#[component]
pub fn CollectionListPage(lang: Language) -> Element {
    let navigator = use_navigator();
    let mut collections: Signal<Vec<Collection>> = Signal::default();
    let mut num_items: Signal<usize> = Signal::default();

    let collections = use_resource(move || async move {
        match list_collections(None, None, Some(0), Some(100)).await {
            Ok(v) => v,
            Err(e) => {
                tracing::error!("failed to fetch collections: {:?}", e);
                vec![]
            }
        }
    })
    .value();

    // FIXME: it needs to be rendered by the server for SSR.
    // let collections = use_server_future(move || async move {
    //     match list_collections(None, None, Some(0), Some(100)).await {
    //         Ok(v) => v,
    //         Err(e) => {
    //             tracing::error!("failed to fetch collections: {:?}", e);
    //             vec![]
    //         }
    //     }
    // })?
    // .value();

    rsx! {
        div {
            class: "w-full h-full",
            GridLayout {
                class: "py-4 lg:py-10",
                if let Some(collections) = collections() {
                    for collection in collections {
                        ImageCard {
                            onclick: move |_evt| {
                                navigator
                                    .push(Route::CollectionDetailPage {
                                        lang: lang.clone(),
                                        agit_id: collection.agit_id.unwrap_or_default(),
                                        collection_id: collection.id,
                                    });
                            },
                            image_url: collection.logo.clone(),
                            p { class: "font-semibold text-2xl pt-4 line-clamp-1", {collection.name.clone()} }
                            p { class: "text-[#666666] font-medium",
                                "Item "
                                span { class: "text-primary ml-1", "{num_items()}" }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Steps To Reproduce**

- Refresh on the component route (e.g. http://localhost:8080/ko/collection/list)
- It causes errors and can't navigate to any webpage.

**Expected behavior**
- Render without errors
- It can navigate to other pages.

**Screenshots**

image

**Environment:**
 - Dioxus version:  `0.6.0-alpha.2`
 - Rust version:   `rustc 1.80.1 (3f5fd8dd4 2024-08-06)`
 - OS info:   `Arch linux 6.11.2`
 - App platform:   fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

### LINKED ISSUE #3299: Double render of element on `use_server_future` when using `asset!()`s
**Problem**

Here is a MRE:

```rs
...

#[component]
fn App() -> Element {
    rsx! {
        document::Link { rel: "icon", href: asset!("/favicon.ico") } // trigger
        Main { }
    }
}

#[component]
fn Main() -> Element {
    let mut items: Signal<Vec<String>> = use_signal(|| Vec::with_capacity(10));
    let init_db_result = use_server_future(move || async move {
        init_db().await.map(|v| {
            spawn(async move { items.set(v) });
        })
    })?;

    if let Err(err) = init_db_result().unwrap() {
        return Err(RenderError::Aborted(dioxus::CapturedError::from_display(
            err,
        )));
    }

    let all_items = {
        let a = items.read().clone().into_iter().map(|x| rsx! { {x} });
        if a.len() == 0 {
            rsx! { "No items" }
        } else {
            rsx! { {a} }
        }
    };

    rsx! {
     p { "List of items:" }
     ul { {all_items} }
    }
}

...
```

If I have any `asset!`s, then I get:

image

If I remove them, then:

image

I tried using https://github.com/DioxusLabs/dioxus/pull/3287 that should potentially fix this.

**Steps To Reproduce**

- get into project dir from [double-render.zip](https://github.com/user-attachments/files/18036637/double-render.zip)
- run `dx serve`
- look at localhost:8080

**Expected behavior**

The content of `ul {}` should be rendered once, not twice.

**Environment:**
 - Dioxus version: https://github.com/DioxusLabs/dioxus/pull/3287/commits/9d6e28b2075c5c1151d5ba32662a25d6bdf98927
 - Rust version: 1.83.0-nightly (fb4aebddd 2024-09-30)
 - OS info: Pop!_OS 22.04
 - App platform: web + fullstack

### PR DESCRIPTION
**Pull request by ealmloff**
The node walker that hydrates streaming fragments in fullstack was walking some nodes twice which took too many ids off of the stack. This PR fixes that issue and adds more debug information for data hydration failures in debug mode

- [x] Verify it fixes my reproduction of #3041
- [x] Check if it fixes ochrons' unreproduced issue in #3041
- [x] Add fullstack playwright test to prevent regressions

Fixes #3041 
Fixes #3299

### CODE REVIEW

File: packages/desktop/src/document.rs [hunk 1]
```diff
@@ -25,6 +30,46 @@ impl Document for DesktopDocument {
     fn set_title(&self, title: String) {
         self.desktop_ctx.window.set_title(&title);
     }
+
+    /// Create a new meta tag in the head
+    fn create_meta(&self, props: MetaProps) {
+        let myself = self.clone();
+        queue_effect(move || {
```
Comment (ealmloff) [inline packages/desktop/src/document.rs:37]: Ideally these would be a default implementation, but it requires a Clone bound on the document trait for queue_effect which is a breaking change

File: packages/core/src/root_wrapper.rs [hunk 2]
```diff
@@ -13,27 +13,26 @@ pub(crate) fn RootScopeWrapper(props: RootProps<VComponent>) -> Element {
         None,
         TEMPLATE,
         Box::new([DynamicNode::Component(
-            fc_to_builder(ErrorBoundary)
-                .children(Element::Ok(VNode::new(
+            fc_to_builder(SuspenseBoundary)
```
Comment (ealmloff) [inline packages/core/src/root_wrapper.rs:16]: This was not causing the hydration error, but putting the error boundary inside the suspense boundary makes it possible to resolve the error on the server without javascript instead of waiting and resolving the error on the client
