### PR TITLE
Refactor and fix eval channels

### LINKED ISSUE #2294: Using recv in js inside an eval on desktop blocks all js if it doesnt have any data to fetch
**Problem**

Currently when you do `eval("await dioxus.recv();")` on desktop and dont send a message it blocks all js from running, including devtool console and events.

**Steps To Reproduce**

Heres the code i used to test it

```rust
#![allow(non_snake_case)]

use dioxus::{desktop::use_window, prelude::*};
use log::LevelFilter;

fn main() {
    // Init debug
    dioxus_logger::init(LevelFilter::Info).expect("failed to init logger");

    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    // Build cool things ✌️
    let windows = use_window();
    use_hook(|| windows.devtool());
    let mut signal = use_signal(|| false);
    use_effect(move || {
        if signal() {
            eval(
                r#"
                    window.alert("1"); 
                    await dioxus.recv(); 
                    window.alert("2");
                "#,
            );
        }
    });

    let onclick = move |_| signal.with_mut(|v| *v = !*v);
    rsx! {
        button {
            onclick,
            "locks js"
        }
        {format!("{}", signal())}
    }
}
```

**Environment:**
 - Dioxus version: 0.5.1
 - Rust version: 1.76.0
 - OS info: MacOS
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

### LINKED ISSUE #2295: Using multiple recv in js inside an eval on web ignores all promises but the last
**Problem**

not completely sure if its intended or not something to care about.

Currently when you do 

```js
dioxus.recv()
  .then((a) => {
    console.log("fulfilled");
  })
  .catch((a) => {
    console.error("rejected");
  }); 
dioxus.recv()
  .then((a) => {
    console.log("fulfilled");
  })
  .catch((a) => {
    console.error("rejected");
  }); 
```

in the js inside an eval in web while theres no messages in the queue it ignores all promises except for the last one

**Steps To Reproduce**

Here is the code i used to test it

```rust
fn main() {
    // Init debug
    dioxus_logger::init(LevelFilter::Info).expect("failed to init logger");
    console_error_panic_hook::set_once();

    launch(App);
}

fn App() -> Element {
    let mut signal = use_signal(|| 0);
    let mut eval2 = use_signal(|| None);
    use_effect(move || {
        if signal() == 1 {
            *eval2.write() = Some(eval(
                r#"
                    dioxus.recv()
                        .then((a) => {
                            console.log("fulfilled");
                        })
                        .catch((a) => {
                            console.error("rejected");
                        }); 
                    dioxus.recv()
                        .then((a) => {
                            console.log("fulfilled");
                        })
                        .catch((a) => {
                            console.error("rejected");
                        }); 
                "#,
            ));
        } else if signal() > 1 {
            let eval2 = eval2().unwrap();
            eval2.send("data".into()).unwrap();
        }
    });

    let onclick = move |_| signal.with_mut(|v| *v += 1);

    rsx! {
        button {
            onclick,
            "locks js"
        }
        {format!("{}", signal())}
    }
}
```

**Expected behavior**

i would expect the promises to be fulfilled in the order they were created in

**Environment:**
 - Dioxus version: 0.5.1
 - Rust version: 1.76.0
 - OS info: MacOS
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

### PR DESCRIPTION
**Pull request by ealmloff**
Platforms working:
- [x] web
- [x] desktop
- [x] Expand headless testing for evals

Fixes #2295
Fixes #2294

Fixes results never sending when returning nothing
Fixes dropping web and desktop evals
Fixes invalid syntax in evals not returning an error

### CODE REVIEW

File: packages/desktop/src/protocol.rs [hunk 1]
```diff
@@ -196,7 +197,7 @@ fn module_loader(root_id: &str, headless: bool) -> String {
     // And then extend it with our native bindings
     {NATIVE_JS}
 
-    // The nativeinterprerter extends the sledgehammer interpreter with a few extra methods that we use for IPC
+    // The native interprerter extends the sledgehammer interpreter with a few extra methods that we use for IPC
```
Comment (DogeDark) [inline packages/desktop/src/protocol.rs:200]: Doc typo, it is ``interpreter``

**Review by DogeDark — CHANGES_REQUESTED** [review]
Looks pretty good to me! I found this typo.

**Review by DogeDark — APPROVED** [review]
